/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MultiPathFinderDialog.java
 *
 * Created on 21-feb-2012, 16.05.52
 */
package it.vige.greenarea.itseasy.routing.swing;

import it.vige.greenarea.itseasy.swing.editor.LogisticsNetEditor;
import it.vige.greenarea.I18N.I18N;
import it.vige.greenarea.dto.GeoLocation;
import it.vige.greenarea.dto.GeoLocationInterface;

import java.awt.event.ActionEvent;

import com.mxgraph.swing.mxGraphComponent;

/**
 * 
 * @author 00917308
 */
public class RouteFinderDialog extends java.awt.Dialog {
	/**
	 * 
	 */
	private static final long serialVersionUID = -8644738023660169840L;
	private LocationInputPanel geoFromPanel;
	private LocationInputPanel geoToPanel;
	private RouteFinderControlPanel controlPanel;
	mxGraphComponent gc;
	GeoLocation geoFrom;
	GeoLocation geoTo;

	/** Creates new form MultiPathFinderDialog */
	public RouteFinderDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		LogisticsNetEditor editor = LogisticsNetEditor.getEditor();
		if (editor == null)
			editor = new LogisticsNetEditor();
		gc = editor.getGraphComponent();
		geoFromPanel = new LocationInputPanel(gc, this);
		routeFinderTabPane.addTab(I18N.getString("SourceNode"), geoFromPanel);
		geoToPanel = new LocationInputPanel(gc, this);
		routeFinderTabPane.addTab(I18N.getString("TargetNode"), geoToPanel);
		controlPanel = new RouteFinderControlPanel(gc, this);
		routeFinderTabPane.addTab(I18N.getString("ControlPanel"), controlPanel);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		routeFinderTabPane = new javax.swing.JTabbedPane();

		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				closeDialog(evt);
			}
		});
		addComponentListener(new java.awt.event.ComponentAdapter() {
			public void componentShown(java.awt.event.ComponentEvent evt) {
				formComponentShown(evt);
			}
		});

		routeFinderTabPane.setPreferredSize(new java.awt.Dimension(546, 466));
		routeFinderTabPane.setRequestFocusEnabled(false);
		add(routeFinderTabPane, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_closeDialog
		setVisible(false);
		dispose();
	}// GEN-LAST:event_closeDialog

	private void formComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_formComponentShown
		geoFromPanel.refreshComponents();
		geoToPanel.refreshComponents();
	}// GEN-LAST:event_formComponentShown

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				RouteFinderDialog dialog = new RouteFinderDialog(
						new java.awt.Frame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {

					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});

			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTabbedPane routeFinderTabPane;

	// End of variables declaration//GEN-END:variables

	public void display(ActionEvent e) {
		this.setVisible(true);
	}

	public void setGeoTo(GeoLocationInterface geoLocation) {
		this.geoToPanel.setSite(geoLocation);
	}

	public void setGeoFrom(GeoLocationInterface geoLocation) {
		this.geoFromPanel.setSite(geoLocation);
	}

	public GeoLocationInterface getGeoFrom() {
		return geoFromPanel.getSite();
	}

	public GeoLocationInterface getGeoTo() {
		return geoToPanel.getSite();
	}
}
