/******************************************************************************
 * Vige, Home of Professional Open Source Copyright 2010, Vige, and           *
 * individual contributors by the @authors tag. See the copyright.txt in the  *
 * distribution for a full listing of individual contributors.                *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may    *
 * not use this file except in compliance with the License. You may obtain    *
 * a copy of the License at http://www.apache.org/licenses/LICENSE-2.0        *
 * Unless required by applicable law or agreed to in writing, software        *
 * distributed under the License is distributed on an "AS IS" BASIS,          *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   *
 * See the License for the specific language governing permissions and        *
 * limitations under the License.                                             *
 ******************************************************************************/
package it.vige.greenarea.itseasy.ln.swing;

import static org.slf4j.LoggerFactory.getLogger;
import it.vige.greenarea.itseasy.swing.editor.LogisticsNetEditor;
import it.vige.greenarea.I18N.I18N;
import it.vige.greenarea.dto.GeoLocation;
import it.vige.greenarea.dto.GeoLocationInterface;
import it.vige.greenarea.geo.GisService;
import it.vige.greenarea.geo.GisService.GeoCodingException;
import it.vige.greenarea.itseasy.ln.swing.LNeditorEventHandlerInterface.LNeditorEvent;
import it.vige.greenarea.itseasy.ln.swing.LNeditorEventHandlerInterface.LNeventType;
import it.vige.greenarea.ln.model.LNSite;

import java.awt.Color;
import java.awt.Dialog;

import javax.swing.JButton;

import org.slf4j.Logger;

import com.mxgraph.model.mxCell;
import com.mxgraph.swing.mxGraphComponent;

public class FullAddressLocationPanel extends javax.swing.JPanel implements
		LNeditorComponentInterface {
	
	private static final long serialVersionUID = 3676534001124058746L;

	private Logger logger = getLogger(getClass());
	
	private LNSite site = new LNSite("XXX");
	private mxCell editingCell;
	private mxGraphComponent graphComponent;
	private GisService gis = null;
	private LNeditorEventHandlerInterface eventHandler;

	/** Creates new form TestTabPanel */
	public FullAddressLocationPanel(mxGraphComponent graphComponent,
			Dialog parent) {
		this.graphComponent = graphComponent;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		saveConfirmDialog = new javax.swing.JDialog();
		dialogMessage = new javax.swing.JLabel();
		okButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();
		provinceField = new javax.swing.JTextField();
		countryLabel1 = new javax.swing.JLabel();
		countryField = new javax.swing.JTextField();
		regionLabel1 = new javax.swing.JLabel();
		regionField = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		cityField = new javax.swing.JTextField();
		jLabel11 = new javax.swing.JLabel();
		streetField = new javax.swing.JTextField();
		jLabel12 = new javax.swing.JLabel();
		numberField = new javax.swing.JTextField();
		jLabel13 = new javax.swing.JLabel();
		latitudeField = new javax.swing.JTextField();
		jLabel14 = new javax.swing.JLabel();
		longitudeField = new javax.swing.JTextField();
		doGeocodeButton = new javax.swing.JButton();
		saveLocationChangeButton = new javax.swing.JButton();
		resetLocationValuesButton = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		zipField = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();

		saveConfirmDialog
				.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		saveConfirmDialog.setAlwaysOnTop(true);
		saveConfirmDialog.setResizable(false);

		dialogMessage.setText(I18N.getString("ConfirmSaveMessage"));

		okButton.setText(I18N.getString("OK"));
		okButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okButtonActionPerformed(evt);
			}
		});

		cancelButton.setText(I18N.getString("Cancel"));
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout saveConfirmDialogLayout = new javax.swing.GroupLayout(
				saveConfirmDialog.getContentPane());
		saveConfirmDialog.getContentPane().setLayout(saveConfirmDialogLayout);
		saveConfirmDialogLayout
				.setHorizontalGroup(saveConfirmDialogLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								saveConfirmDialogLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												saveConfirmDialogLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																dialogMessage,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																376,
																Short.MAX_VALUE)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																saveConfirmDialogLayout
																		.createSequentialGroup()
																		.addComponent(
																				cancelButton)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				okButton)))
										.addContainerGap()));
		saveConfirmDialogLayout
				.setVerticalGroup(saveConfirmDialogLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								saveConfirmDialogLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(dialogMessage)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												233, Short.MAX_VALUE)
										.addGroup(
												saveConfirmDialogLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(okButton)
														.addComponent(
																cancelButton))
										.addContainerGap()));

		provinceField.setText("jTextField1");
		provinceField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				provinceFieldKeyTyped(evt);
			}
		});

		countryLabel1
				.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		countryLabel1.setText(I18N.getString("Country"));
		countryLabel1
				.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

		countryField.setText("jTextField2");
		countryField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				countryFieldKeyTyped(evt);
			}
		});

		regionLabel1
				.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		regionLabel1.setText(I18N.getString("Region"));
		regionLabel1
				.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

		regionField.setText("jTextField1");
		regionField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				regionFieldKeyTyped(evt);
			}
		});

		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel3.setText(I18N.getString("City"));
		jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

		cityField.setText("jTextField1");
		cityField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				cityFieldKeyTyped(evt);
			}
		});

		jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel11.setText(I18N.getString("Street"));

		streetField.setText("jTextField1");
		streetField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				streetFieldKeyTyped(evt);
			}
		});

		jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel12.setText(I18N.getString("Number"));

		numberField.setText("jTextField1");
		numberField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				numberFieldKeyTyped(evt);
			}
		});

		jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel13.setText(I18N.getString("Latitude"));

		latitudeField.setEditable(false);
		latitudeField.setText("jTextField1");
		latitudeField.setFocusable(false);

		jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel14.setText(I18N.getString("Longitude"));

		longitudeField.setEditable(false);
		longitudeField.setText("jTextField1");
		longitudeField.setFocusable(false);

		doGeocodeButton.setText(I18N.getString("GeoCodeAction"));
		doGeocodeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				doGeocodeButtonActionPerformed(evt);
			}
		});

		saveLocationChangeButton.setText(I18N.getString("Save"));
		saveLocationChangeButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						saveLocationChangeButtonActionPerformed(evt);
					}
				});

		resetLocationValuesButton.setText(I18N.getString("RESET"));
		resetLocationValuesButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						resetLocationValuesButtonActionPerformed(evt);
					}
				});

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel1.setText(I18N.getString("ZIP"));

		zipField.setText("jTextField1");

		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel2.setText(I18N.getString("Province"));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(49, 49, 49)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														resetLocationValuesButton)
												.addComponent(
														saveLocationChangeButton)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(35,
																										35,
																										35)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																																.addComponent(
																																		countryLabel1)
																																.addComponent(
																																		regionLabel1)
																																.addComponent(
																																		jLabel1)
																																.addComponent(
																																		jLabel12)
																																.addComponent(
																																		jLabel11)
																																.addComponent(
																																		jLabel3))
																												.addComponent(
																														jLabel2,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														77,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(18,
																										18,
																										18)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						regionField,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						250,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						countryField,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						250,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						zipField,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						250,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						streetField,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						250,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						cityField,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						250,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						provinceField,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						250,
																																						Short.MAX_VALUE))
																																.addGap(21,
																																		21,
																																		21))
																												.addComponent(
																														numberField,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														120,
																														javax.swing.GroupLayout.PREFERRED_SIZE)))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										doGeocodeButton,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										152,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(18,
																										18,
																										18)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																												.addComponent(
																														latitudeField)
																												.addComponent(
																														longitudeField,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														144,
																														Short.MAX_VALUE))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel13)
																												.addComponent(
																														jLabel14))))
																.addGap(144,
																		144,
																		144)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(35, 35, 35)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														countryField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(countryLabel1))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														regionField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(regionLabel1))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														provinceField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										8, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														cityField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														streetField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel11))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel12)
												.addComponent(
														numberField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														zipField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						longitudeField,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel14,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						16,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(13, 13,
																		13))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						doGeocodeButton)
																				.addComponent(
																						latitudeField,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel13))
																.addGap(43, 43,
																		43)))
								.addComponent(resetLocationValuesButton)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(saveLocationChangeButton)
								.addGap(25, 25, 25)));
	}// </editor-fold>//GEN-END:initComponents

	private void addressChangedEvent() {
		enableButton(doGeocodeButton);
		latitudeField.setText("0.0");
		longitudeField.setText("0.0");
		disableButton(saveLocationChangeButton);
		enableButton(resetLocationValuesButton);
	}

	private void countryFieldKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_countryFieldKeyTyped
		addressChangedEvent();
	}// GEN-LAST:event_countryFieldKeyTyped

	private void regionFieldKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_regionFieldKeyTyped
		addressChangedEvent();
	}// GEN-LAST:event_regionFieldKeyTyped

	private void cityFieldKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_cityFieldKeyTyped
		addressChangedEvent();
	}// GEN-LAST:event_cityFieldKeyTyped

	private void streetFieldKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_streetFieldKeyTyped
		addressChangedEvent();
	}// GEN-LAST:event_streetFieldKeyTyped

	private void numberFieldKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_numberFieldKeyTyped
		addressChangedEvent();
	}// GEN-LAST:event_numberFieldKeyTyped

	private void doGeocodeButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_doGeocodeButtonActionPerformed
		disableButton(doGeocodeButton);
		if (gis == null)
			gis = LogisticsNetEditor.getGisService();
		GeoLocation gl = new GeoLocation(0., 0.);
		GeoLocationInterface gli;
		saveLocationData(gl);
		try {
			gli = gis.geoCode(gl);
			disableButton(doGeocodeButton);
			countryField.setText(gli.getCountry());
			regionField.setText(gli.getAdminAreaLevel1());
			provinceField.setText(gli.getAdminAreaLevel2());
			cityField.setText(gli.getCity());
			streetField.setText(gli.getStreet());
			numberField.setText(gli.getNumber());
			zipField.setText(gli.getZipCode());
			latitudeField.setText(Double.toString(gli.getLatitude()));
			longitudeField.setText(Double.toString(gli.getLongitude()));
			enableButton(saveLocationChangeButton);
		} catch (GeoCodingException ex) {
			logger.error("logistic editor", ex);
		}

	}// GEN-LAST:event_doGeocodeButtonActionPerformed

	private void saveLocationChangeButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saveLocationChangeButtonActionPerformed
		doConfirmDialog();
	}// GEN-LAST:event_saveLocationChangeButtonActionPerformed

	private void doConfirmDialog() {
		saveConfirmDialog.setSize(347, 101);
		saveConfirmDialog.setVisible(true);
		this.setEnabled(false);
	}

	private void resetLocationValuesButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resetLocationValuesButtonActionPerformed
		displayLocation(site);
		disableButton(saveLocationChangeButton);
		disableButton(doGeocodeButton);
		disableButton(resetLocationValuesButton);
	}// GEN-LAST:event_resetLocationValuesButtonActionPerformed

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_okButtonActionPerformed
		// site.loadElement((Element) editingCell.getValue());
		site = (LNSite) editingCell.getValue();
		saveLocationData(site);
		graphComponent.labelChanged(editingCell, site, evt);
		saveConfirmDialog.setVisible(false);
		this.setEnabled(true);
		disableButton(saveLocationChangeButton);
		disableButton(resetLocationValuesButton);
		if (eventHandler != null)
			eventHandler.handleEvent(new LNeditorEvent(LNeventType.save, site,
					null));
	}// GEN-LAST:event_okButtonActionPerformed

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
		saveConfirmDialog.setVisible(false);
		this.setEnabled(true);
		if (eventHandler != null)
			eventHandler.handleEvent(new LNeditorEvent(LNeventType.cancel,
					null, null));
	}// GEN-LAST:event_cancelButtonActionPerformed

	private void provinceFieldKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_provinceFieldKeyTyped
		addressChangedEvent();
	}// GEN-LAST:event_provinceFieldKeyTyped

	private void disableButton(JButton b) {
		b.setEnabled(false);
		b.setForeground(Color.gray);
	}

	private void enableButton(JButton b) {
		b.setEnabled(true);
		b.setForeground(Color.black);
	}

	private void displayLocation(GeoLocationInterface site) {
		countryField.setText(site.getCountry());
		regionField.setText(site.getAdminAreaLevel1());
		provinceField.setText(site.getAdminAreaLevel2());
		cityField.setText(site.getCity());
		streetField.setText(site.getStreet());
		numberField.setText(site.getNumber());
		zipField.setText(site.getZipCode());
		latitudeField.setText(Double.toString(site.getLatitude()));
		longitudeField.setText(Double.toString(site.getLongitude()));
	}

	private void saveLocationData(GeoLocationInterface site) {
		site.setCountry(countryField.getText());
		site.setAdminAreaLevel1(regionField.getText());
		site.setAdminAreaLevel2(provinceField.getText());
		site.setCity(cityField.getText());
		site.setStreet(streetField.getText());
		site.setNumber(numberField.getText());
		site.setZipCode(zipField.getText());
		site.setLatitude(Double.parseDouble(latitudeField.getText()));
		site.setLongitude(Double.parseDouble(longitudeField.getText()));
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton cancelButton;
	private javax.swing.JTextField cityField;
	private javax.swing.JTextField countryField;
	private javax.swing.JLabel countryLabel1;
	private javax.swing.JLabel dialogMessage;
	private javax.swing.JButton doGeocodeButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JTextField latitudeField;
	private javax.swing.JTextField longitudeField;
	private javax.swing.JTextField numberField;
	private javax.swing.JButton okButton;
	private javax.swing.JTextField provinceField;
	private javax.swing.JTextField regionField;
	private javax.swing.JLabel regionLabel1;
	private javax.swing.JButton resetLocationValuesButton;
	private javax.swing.JDialog saveConfirmDialog;
	private javax.swing.JButton saveLocationChangeButton;
	private javax.swing.JTextField streetField;
	private javax.swing.JTextField zipField;

	// End of variables declaration//GEN-END:variables

	void startEditing(Object cell) {
		editingCell = (mxCell) cell;
		// site.loadElement((Element) editingCell.getValue());
		site = (LNSite) editingCell.getValue();
		displayLocation(site);
		disableButton(saveLocationChangeButton);
		disableButton(doGeocodeButton);
		disableButton(resetLocationValuesButton);
	}

	@Override
	public void addListener(LNeditorEventHandlerInterface h) {
		eventHandler = h;
	}

	@Override
	public boolean isChanged() {
		throw new UnsupportedOperationException("Not supported yet.");
	}

	@Override
	public Object getUserObject() {
		return site;
	}
}
