/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LNCarrierEditor.java
 *
 * Created on 21-lug-2011, 11.13.16
 */
package it.vige.greenarea.itseasy.ln.swing;

import com.mxgraph.model.mxCell;
import com.mxgraph.swing.mxGraphComponent;
import com.mxgraph.swing.view.mxICellEditor;
import java.util.EventObject;

/**
 * 
 * @author 00917308
 */
public class LNCarrierEditor extends javax.swing.JFrame implements
		mxICellEditor {
	/**
	 * 
	 */
	private static final long serialVersionUID = -3146882323419248106L;
	private mxGraphComponent graphComponent;
	private mxCell editingCell;

	/** Creates new form LNCarrierEditor */
	public LNCarrierEditor(mxGraphComponent gc) {
		graphComponent = gc;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

		jButton1.setText("jButton1");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap(264, Short.MAX_VALUE)
						.addComponent(jButton1).addGap(57, 57, 57)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap(182, Short.MAX_VALUE)
						.addComponent(jButton1).addGap(93, 93, 93)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				// new LNCarrierEditor().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;

	// End of variables declaration//GEN-END:variables

	@Override
	public Object getEditingCell() {
		return editingCell;
	}

	@Override
	public void startEditing(Object cell, EventObject trigger) {
		editingCell = (mxCell) cell;
		graphComponent.setEnabled(false);
		this.setVisible(true);
	}

	@Override
	public void stopEditing(boolean cancel) {
		this.setVisible(false);
		graphComponent.setEnabled(true);
	}
}
