/******************************************************************************
 * Vige, Home of Professional Open Source Copyright 2010, Vige, and           *
 * individual contributors by the @authors tag. See the copyright.txt in the  *
 * distribution for a full listing of individual contributors.                *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may    *
 * not use this file except in compliance with the License. You may obtain    *
 * a copy of the License at http://www.apache.org/licenses/LICENSE-2.0        *
 * Unless required by applicable law or agreed to in writing, software        *
 * distributed under the License is distributed on an "AS IS" BASIS,          *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   *
 * See the License for the specific language governing permissions and        *
 * limitations under the License.                                             *
 ******************************************************************************/
package it.vige.greenarea.itseasy.ln.swing;

import com.mxgraph.model.mxCell;
import com.mxgraph.swing.mxGraphComponent;
import com.mxgraph.swing.view.mxICellEditor;
import java.util.EventObject;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;

public abstract class LNCellEditorDialog extends java.awt.Dialog implements
		mxICellEditor, SaveConfirmHandlerInterface {
	/**
	 * 
	 */
	private static final long serialVersionUID = -8851769454563755478L;
	protected mxGraphComponent graphComponent;
	protected mxCell editingCell;
	protected SaveConfirmDialog scd;
	protected boolean changed;

	public void setEditingCell(mxCell editingCell) {
		this.editingCell = editingCell;
	}

	public mxGraphComponent getGraphComponent() {
		return graphComponent;
	}

	public JTabbedPane getEditorTabPanel() {
		return editorTabPanel;
	}

	public abstract void onDisplay(Object o);

	public abstract void onClose(Object o);

	public abstract boolean isChanged();

	/** Creates new form LNCellEditorDialog */
	protected LNCellEditorDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	public LNCellEditorDialog(mxGraphComponent gc) {
		this((JFrame) SwingUtilities.windowForComponent(gc), false);
		this.graphComponent = gc;
		scd = new SaveConfirmDialog(
				(JFrame) SwingUtilities.windowForComponent(gc), true);
		scd.setEventHandler(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		editorTabPanel = new javax.swing.JTabbedPane();

		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				closeDialog(evt);
			}
		});
		addComponentListener(new java.awt.event.ComponentAdapter() {
			public void componentHidden(java.awt.event.ComponentEvent evt) {
				formComponentHidden(evt);
			}

			public void componentShown(java.awt.event.ComponentEvent evt) {
				formComponentShown(evt);
			}
		});

		editorTabPanel.setPreferredSize(new java.awt.Dimension(400, 300));
		add(editorTabPanel, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_closeDialog
		if (isChanged())
			scd.setVisible(true);
		else
			stopEditing(true);
	}// GEN-LAST:event_closeDialog

	private void formComponentHidden(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_formComponentHidden

	}// GEN-LAST:event_formComponentHidden

	private void formComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_formComponentShown
		try {
			this.onDisplay(editingCell.getValue());
		} catch (Exception ex) {
			// TODO
		}
	}// GEN-LAST:event_formComponentShown

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTabbedPane editorTabPanel;

	// End of variables declaration//GEN-END:variables

	@Override
	public Object getEditingCell() {
		return this.editingCell;
	}

	@Override
	public void startEditing(Object cell, EventObject trigger) {
		if (cell instanceof mxCell)
			editingCell = (mxCell) cell;
		graphComponent.setEnabled(false);
		this.setVisible(true);
	}

	@Override
	public void stopEditing(boolean cancel) {
		if (editingCell != null) {
			if (!cancel)
				graphComponent.labelChanged(editingCell,
						editingCell.getValue(), null);
			editingCell = null;
			graphComponent.setEnabled(true);
			this.setVisible(false);
		}
	}

	@Override
	public void confirmEvent(Boolean ok) {
		if (ok) {
			this.saveData(editingCell.getValue());
		}
		stopEditing(false);
	}

	public abstract void saveData(Object o);
}
