/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimpleNamePanel.java
 *
 * Created on 20-mar-2012, 12.36.25
 */
package it.vige.greenarea.itseasy.ln.swing;

import it.vige.greenarea.I18N.I18N;

/**
 * 
 * @author 00917308
 */
public class SimpleNamePanel extends javax.swing.JPanel {
	/**
	 * 
	 */
	private static final long serialVersionUID = 7406859123436956262L;
	protected boolean changed;

	public boolean isChanged() {
		return changed;
	}

	public void setChanged(boolean changed) {
		this.changed = changed;
	}

	/** Creates new form SimpleNamePanel */
	public SimpleNamePanel() {
		initComponents();
		nameField.setText("");
		descriptionField.setText("");
		changed = false;
	}

	public String getCellName() {
		return nameField.getText();
	}

	public void setCellName(String cellName) {
		nameField.setText(cellName);
	}

	public String getDescription() {
		return descriptionField.getText();
	}

	public void setDescription(String description) {
		descriptionField.setText(description);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		nameField = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		descriptionField = new javax.swing.JTextArea();
		jLabel2 = new javax.swing.JLabel();

		nameField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				nameFieldKeyTyped(evt);
			}
		});

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel1.setText(I18N.getString("NameFieldLabel"));

		descriptionField.setColumns(20);
		descriptionField.setRows(5);
		descriptionField.setText(getDescription());
		descriptionField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				descriptionFieldKeyTyped(evt);
			}
		});
		jScrollPane1.setViewportView(descriptionField);

		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel2.setText(I18N.getString("DescriptionFieldLabel"));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														jLabel1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														98, Short.MAX_VALUE)
												.addComponent(
														jLabel2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														98, Short.MAX_VALUE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														263, Short.MAX_VALUE)
												.addComponent(
														nameField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														263,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(22, 22, 22)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														nameField,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														110,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(113, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void nameFieldKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_nameFieldKeyTyped
		changed = true;
	}// GEN-LAST:event_nameFieldKeyTyped

	private void descriptionFieldKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_descriptionFieldKeyTyped
		changed = true;
	}// GEN-LAST:event_descriptionFieldKeyTyped

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextArea descriptionField;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField nameField;

	// End of variables declaration//GEN-END:variables

	void startEditing(Object cell) {

	}

	void stopEditing(boolean cancel) {

	}

}
